local wezterm = require("wezterm")
local act     = wezterm.action
local mux     = wezterm.mux

-- Config directory (sibling files live here)
local CFG_DIR     = wezterm.config_dir
local STATE_FILE  = CFG_DIR .. "/session_state.lua"
local PROJECTS    = dofile(CFG_DIR .. "/projects.lua")

local BASH = "C:/Program Files/Git/bin/bash.exe"

-- ─────────────────────────────────────────────────────────────────────────────
-- Session state helpers
-- Read: dofile the auto-generated state table (or return nil if missing/invalid)
-- Write: serialize the current workspace+tab layout to a Lua return table
-- ─────────────────────────────────────────────────────────────────────────────

local function read_session_state()
  local ok, result = pcall(dofile, STATE_FILE)
  if ok and type(result) == "table" then return result end
  return nil
end

local function serialize_value(v, indent)
  indent = indent or ""
  local t = type(v)
  if t == "nil"     then return "nil"
  elseif t == "boolean" then return tostring(v)
  elseif t == "number"  then return tostring(v)
  elseif t == "string"  then return string.format("%q", v)
  elseif t == "table"   then
    local inner = indent .. "  "
    local parts = {}
    local is_array = #v > 0
    if is_array then
      for _, item in ipairs(v) do
        table.insert(parts, inner .. serialize_value(item, inner))
      end
      return "{\n" .. table.concat(parts, ",\n") .. "\n" .. indent .. "}"
    else
      for k, val in pairs(v) do
        local key = type(k) == "string"
            and ("[" .. string.format("%q", k) .. "]")
            or  ("[" .. tostring(k) .. "]")
        table.insert(parts, inner .. key .. " = " .. serialize_value(val, inner))
      end
      return "{\n" .. table.concat(parts, ",\n") .. "\n" .. indent .. "}"
    end
  end
  return "nil"
end

local function write_session_state(state)
  local f = io.open(STATE_FILE, "w")
  if not f then return end
  f:write("-- auto-generated by wezterm — do not hand-edit\n")
  f:write("return " .. serialize_value(state) .. "\n")
  f:close()
end

-- Capture current layout across all windows/workspaces
local function capture_state()
  local state = { active_workspace = mux.get_active_workspace(), workspaces = {} }
  for _, win in ipairs(mux.all_windows()) do
    local ws = win:get_workspace()
    if not state.workspaces[ws] then
      local tabs_state = {}
      for tab_idx, tab in ipairs(win:tabs()) do
        local pane    = tab:active_pane()
        local cwd_uri = pane:get_current_working_dir()
        local cwd_str = cwd_uri and cwd_uri.file_path or ""
        -- Find the project tab definition for this workspace+tab to know its resume flag
        local resume_cmd = nil
        for _, proj in ipairs(PROJECTS) do
          if proj.id == ws and proj.tabs[tab_idx] and proj.tabs[tab_idx].resume then
            resume_cmd = proj.tabs[tab_idx].cmd
          end
        end
        table.insert(tabs_state, {
          title      = tab:get_title(),
          cwd        = cwd_str,
          resume_cmd = resume_cmd,
          tab_idx    = tab_idx - 1,
        })
      end
      state.workspaces[ws] = {
        active_tab = win:active_tab():tab_id(),
        tabs       = tabs_state,
      }
    end
  end
  return state
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Startup: open a single plain shell. Workspaces are spawned on-demand.
-- ─────────────────────────────────────────────────────────────────────────────

wezterm.on("gui-startup", function(_cmd)
  mux.spawn_window({ args = { BASH, "-l" } })
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- open_project: switch to a workspace, spawning it with full tab layout if new.
-- ─────────────────────────────────────────────────────────────────────────────

local function workspace_exists(id)
  for _, win in ipairs(mux.all_windows()) do
    if win:get_workspace() == id then return true end
  end
  return false
end

local function open_project(proj_id)
  return wezterm.action_callback(function(window, pane)
    if workspace_exists(proj_id) then
      window:perform_action(act.SwitchToWorkspace { name = proj_id }, pane)
      return
    end

    local proj = nil
    for _, p in ipairs(PROJECTS) do
      if p.id == proj_id then proj = p; break end
    end
    if not proj then return end

    local saved = read_session_state()
    local t1    = proj.tabs[1]
    local t1_args = t1.cmd and { BASH, "-lc", t1.cmd } or { BASH, "-l" }
    if saved and saved.workspaces and saved.workspaces[proj_id] then
      local st = saved.workspaces[proj_id].tabs and saved.workspaces[proj_id].tabs[1]
      if st and st.resume_cmd then t1_args = { BASH, "-lc", st.resume_cmd } end
    end

    local tab, _, win = mux.spawn_window({
      workspace = proj_id,
      cwd       = proj.cwd,
      args      = t1_args,
    })
    tab:set_title(t1.title)

    for j = 2, #proj.tabs do
      local t    = proj.tabs[j]
      local args = t.cmd and { BASH, "-lc", t.cmd } or { BASH, "-l" }
      if saved and saved.workspaces and saved.workspaces[proj_id] then
        local st = saved.workspaces[proj_id].tabs and saved.workspaces[proj_id].tabs[j]
        if st and st.resume_cmd then args = { BASH, "-lc", st.resume_cmd } end
      end
      local new_tab, _ = win:spawn_tab({ cwd = proj.cwd, args = args })
      new_tab:set_title(t.title)
    end

    tab:activate()
    window:perform_action(act.SwitchToWorkspace { name = proj_id }, pane)
  end)
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Periodic state flush (every 30s) so abrupt kills don't lose context
-- ─────────────────────────────────────────────────────────────────────────────

local function schedule_state_flush()
  wezterm.time.call_after(30, function()
    write_session_state(capture_state())
    schedule_state_flush() -- reschedule indefinitely
  end)
end

wezterm.on("gui-attached", function(_domain)
  schedule_state_flush()
end)

-- Also flush on graceful close
wezterm.on("window-close-requested", function(window, _pane)
  write_session_state(capture_state())
  window:perform_action(act.CloseCurrentWindow, window:active_pane())
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- Appearance
-- ─────────────────────────────────────────────────────────────────────────────

local config = wezterm.config_builder()

-- ── Crimson Noir — custom palette ────────────────────────────────────────────
-- To swap back to a built-in: comment out config.colors and set config.color_scheme instead.
config.colors = {
  -- Base layer
  background    = "#0e0014",  -- purple-black void
  foreground    = "#edd9f5",  -- warm purple-tinted white

  cursor_bg     = "#c4185c",  -- saturated crimson-magenta
  cursor_fg     = "#0e0014",
  cursor_border = "#c4185c",

  selection_bg  = "#8b1aaa",  -- regal purple selection
  selection_fg  = "#edd9f5",

  split         = "#6b3080",  -- pane divider

  -- 16 ANSI slots — programs write to these for syntax / git / ls colors
  --   slot 0  black      slot 1  red        slot 2  green      slot 3  yellow
  --   slot 4  blue       slot 5  magenta    slot 6  cyan       slot 7  white
  ansi = {
    "#200030",  -- 0  black  (used as bg variant in some apps)
    "#c4185c",  -- 1  red    → our crimson-magenta (errors, deletions)
    "#1f8c5a",  -- 2  green  → muted forest green  (additions, success)
    "#b87333",  -- 3  yellow → copper-gold          (warnings, modified)
    "#2a6fa8",  -- 4  blue   → steel blue           (info, types)
    "#8b1aaa",  -- 5  magenta→ deep regal purple    (keywords, specials)
    "#2a7a8c",  -- 6  cyan   → dark teal            (strings, paths)
    "#c8b8d8",  -- 7  white  → purple-tinted grey   (normal text)
  },
  brights = {
    "#6b3080",  -- 8  bright black  (comments, borders)
    "#e8378e",  -- 9  bright red    → hot rose-red   (bold errors)
    "#27b870",  -- 10 bright green  → vivid green    (bold success)
    "#d4943a",  -- 11 bright yellow → warm amber     (bold warnings)
    "#4a9fd4",  -- 12 bright blue   → sky blue       (bold info)
    "#b040d0",  -- 13 bright magenta→ vivid purple   (bold specials)
    "#3aadcc",  -- 14 bright cyan   → vivid teal     (bold strings)
    "#edd9f5",  -- 15 bright white  → primary text   (bold normal)
  },

  -- Tab bar
  tab_bar = {
    background = "#160022",
    active_tab = {
      bg_color  = "#0e0014",
      fg_color  = "#e8378e",
      intensity = "Bold",
    },
    inactive_tab = {
      bg_color = "#160022",
      fg_color = "#6b3080",
    },
    inactive_tab_hover = {
      bg_color = "#200030",
      fg_color = "#c8b8d8",
    },
  },
}
config.font              = wezterm.font("JetBrains Mono", { weight = "Regular" })
config.font_size         = 13.0
config.line_height       = 1.1
config.use_fancy_tab_bar = false
config.tab_bar_at_bottom = true
config.tab_max_width     = 22
config.show_new_tab_button_in_tab_bar = false
config.window_padding    = { left = 6, right = 6, top = 4, bottom = 4 }
config.window_decorations = "RESIZE"
config.initial_cols      = 220
config.initial_rows      = 52
config.default_cursor_style = "BlinkingBar"
config.cursor_blink_rate = 500
config.scrollback_lines  = 20000
config.audible_bell      = "Disabled"
config.default_prog      = { BASH, "-l" }

-- ─────────────────────────────────────────────────────────────────────────────
-- Status bar: workspace name + clock
-- ─────────────────────────────────────────────────────────────────────────────

wezterm.on("update-right-status", function(window, _pane)
  local ws   = window:active_workspace()
  local time = wezterm.strftime "%H:%M"
  window:set_right_status(wezterm.format({
    { Attribute = { Intensity = "Bold" } },
    { Foreground = { Color = "#7aa2f7" } },
    { Text = "  " .. ws },
    { Foreground = { Color = "#565f89" } },
    { Text = "  " .. time .. "  " },
  }))
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- Tab title renderer
-- ─────────────────────────────────────────────────────────────────────────────

wezterm.on("format-tab-title", function(tab, _tabs, _panes, _cfg, _hover, max_width)
  local title = tab.tab_title
  if not title or #title == 0 then title = tab.active_pane.title end
  if #title > max_width - 4 then
    title = wezterm.truncate_right(title, max_width - 4)
  end
  local idx = tab.tab_index + 1
  return {
    { Background = { Color = tab.is_active and "#1a1b26" or "#16161e" } },
    { Foreground = { Color = tab.is_active and "#c0caf5" or "#565f89" } },
    { Text = " " .. idx .. ":" .. title .. " " },
  }
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- Key bindings
-- LEADER = CTRL+SPACE  (1.5 s window for the chord key)
-- ─────────────────────────────────────────────────────────────────────────────

config.leader = { key = "Space", mods = "CTRL", timeout_milliseconds = 1500 }

-- Build workspace-switcher choices list at config load time
local ws_choices = {}
for i, p in ipairs(PROJECTS) do
  table.insert(ws_choices, {
    id    = p.id,
    label = string.format("[%d] %s", i, p.label),
  })
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Macro legend (shown by LEADER ?)
-- Add any new binding here alongside its keys entry below so the legend stays in sync.
-- ─────────────────────────────────────────────────────────────────────────────

local LEGEND = {
  { keys = "LEADER  w",         desc = "Open project workspace (fuzzy picker)" },
  { keys = "LEADER  1-7",       desc = "Jump directly to project 1–7" },
  { keys = "LEADER  [ / ]",     desc = "Cycle workspaces prev / next" },
  { keys = "──────────────────────", desc = "─── Tabs ───────────────────────" },
  { keys = "CTRL+ALT  1-4",     desc = "Jump to tab 1–4 in current workspace" },
  { keys = "CTRL+SHIFT  H / L", desc = "Previous / next tab" },
  { keys = "CTRL+SHIFT  T",     desc = "New tab (same directory)" },
  { keys = "CTRL+SHIFT  W",     desc = "Close current tab" },
  { keys = "──────────────────────", desc = "─── Panes ──────────────────────" },
  { keys = "LEADER  |",         desc = "Split pane right" },
  { keys = "LEADER  -",         desc = "Split pane down" },
  { keys = "LEADER  h/j/k/l",   desc = "Move between panes (vim-style)" },
  { keys = "LEADER  z",         desc = "Zoom / unzoom active pane" },
  { keys = "──────────────────────", desc = "─── Stock Research macros ──────" },
  { keys = "LEADER  r",         desc = "Registry regen (generate_live_registry)" },
  { keys = "LEADER  b",         desc = "Broad sweep (backtest_broad_sweep)" },
  { keys = "LEADER  s",         desc = "System report" },
  { keys = "LEADER  p",         desc = "Tail paper engine log" },
  { keys = "──────────────────────", desc = "─── Web project macros ─────────" },
  { keys = "LEADER  d",         desc = "pnpm dev" },
  { keys = "LEADER  i",         desc = "pnpm install" },
  { keys = "──────────────────────", desc = "─── Utility ────────────────────" },
  { keys = "LEADER  n",         desc = "Fire toast: task complete (current workspace)" },
  { keys = "LEADER  c",         desc = "Copy mode (vi-style scroll + select)" },
  { keys = "LEADER  f",         desc = "Search scrollback" },
  { keys = "CTRL+SHIFT  C",     desc = "Copy to clipboard" },
  { keys = "CTRL+SHIFT  V",     desc = "Paste from clipboard" },
  { keys = "CTRL+SHIFT  F",     desc = "Toggle full-screen" },
  { keys = "CTRL+SHIFT  L",     desc = "Clear scrollback" },
  { keys = "CTRL  + / - / 0",   desc = "Font size increase / decrease / reset" },
  { keys = "LEADER  ?",         desc = "Show this legend" },
}

local legend_choices = {}
for _, entry in ipairs(LEGEND) do
  table.insert(legend_choices, {
    id    = "",
    label = string.format("%-28s  %s", entry.keys, entry.desc),
  })
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Key table
-- ─────────────────────────────────────────────────────────────────────────────

config.keys = {

  -- ── Legend overlay ────────────────────────────────────────────────────────
  {
    key = "?", mods = "LEADER",
    action = act.InputSelector {
      title   = "Key Bindings — press Esc to dismiss",
      choices = legend_choices,
      fuzzy   = true,
      -- No action on select — this is read-only reference
      action  = wezterm.action_callback(function(_win, _pane, _id, _label) end),
    },
  },

  -- ── Workspace switching ───────────────────────────────────────────────────
  {
    key = "w", mods = "LEADER",
    action = act.InputSelector {
      title   = "Open Project Workspace",
      choices = ws_choices,
      fuzzy   = true,
      action  = wezterm.action_callback(function(window, pane, id, _label)
        if id and id ~= "" then
          window:perform_action(open_project(id), pane)
        end
      end),
    },
  },

  { key = "1", mods = "LEADER", action = open_project(PROJECTS[1].id) },
  { key = "2", mods = "LEADER", action = open_project(PROJECTS[2].id) },
  { key = "3", mods = "LEADER", action = open_project(PROJECTS[3].id) },
  { key = "4", mods = "LEADER", action = open_project(PROJECTS[4].id) },
  { key = "5", mods = "LEADER", action = open_project(PROJECTS[5].id) },
  { key = "6", mods = "LEADER", action = open_project(PROJECTS[6].id) },
  { key = "7", mods = "LEADER", action = open_project(PROJECTS[7].id) },
  { key = "[", mods = "LEADER", action = act.SwitchWorkspaceRelative(-1) },
  { key = "]", mods = "LEADER", action = act.SwitchWorkspaceRelative(1)  },

  -- ── Tab navigation ────────────────────────────────────────────────────────
  { key = "1", mods = "CTRL|ALT",   action = act.ActivateTab(0) },
  { key = "2", mods = "CTRL|ALT",   action = act.ActivateTab(1) },
  { key = "3", mods = "CTRL|ALT",   action = act.ActivateTab(2) },
  { key = "4", mods = "CTRL|ALT",   action = act.ActivateTab(3) },
  { key = "h", mods = "CTRL|SHIFT", action = act.ActivateTabRelative(-1) },
  { key = "l", mods = "CTRL|SHIFT", action = act.ActivateTabRelative(1)  },
  { key = "t", mods = "CTRL|SHIFT", action = act.SpawnTab "CurrentPaneDomain" },
  { key = "w", mods = "CTRL|SHIFT", action = act.CloseCurrentTab { confirm = true } },

  -- ── Pane management ───────────────────────────────────────────────────────
  { key = "|", mods = "LEADER",     action = act.SplitHorizontal { domain = "CurrentPaneDomain" } },
  { key = "-", mods = "LEADER",     action = act.SplitVertical   { domain = "CurrentPaneDomain" } },
  { key = "h", mods = "LEADER",     action = act.ActivatePaneDirection "Left"  },
  { key = "j", mods = "LEADER",     action = act.ActivatePaneDirection "Down"  },
  { key = "k", mods = "LEADER",     action = act.ActivatePaneDirection "Up"    },
  { key = "l", mods = "LEADER",     action = act.ActivatePaneDirection "Right" },
  { key = "z", mods = "LEADER",     action = act.TogglePaneZoomState },

  -- ── Stock Research macros ─────────────────────────────────────────────────
  { key = "r", mods = "LEADER",     action = act.SendString "python scripts/generate_live_registry.py --all\n" },
  { key = "b", mods = "LEADER",     action = act.SendString "python scripts/backtest_broad_sweep.py\n" },
  { key = "s", mods = "LEADER",     action = act.SendString "python scripts/system_report.py\n" },
  { key = "p", mods = "LEADER",     action = act.SendString "tail -f live_trading/logs/paper_engine.log\n" },

  -- ── Web project macros ────────────────────────────────────────────────────
  { key = "d", mods = "LEADER",     action = act.SendString "pnpm dev\n" },
  { key = "i", mods = "LEADER",     action = act.SendString "pnpm install\n" },

  -- ── Notifications ─────────────────────────────────────────────────────────
  {
    key = "n", mods = "LEADER",
    action = wezterm.action_callback(function(window, _pane)
      local ws = window:active_workspace()
      window:toast_notification("WezTerm", ws .. " — task complete", nil, 5000)
    end),
  },

  -- ── Utility ───────────────────────────────────────────────────────────────
  { key = "c", mods = "LEADER",      action = act.ActivateCopyMode },
  { key = "f", mods = "LEADER",      action = act.Search { CaseSensitiveString = "" } },
  { key = "c", mods = "CTRL|SHIFT",  action = act.CopyTo "Clipboard" },
  { key = "v", mods = "CTRL|SHIFT",  action = act.PasteFrom "Clipboard" },
  { key = "f", mods = "CTRL|SHIFT",  action = act.ToggleFullScreen },
  { key = "l", mods = "CTRL|SHIFT",  action = act.ClearScrollback "ScrollbackAndViewport" },
  { key = "=", mods = "CTRL",        action = act.IncreaseFontSize },
  { key = "-", mods = "CTRL",        action = act.DecreaseFontSize },
  { key = "0", mods = "CTRL",        action = act.ResetFontSize },
}

-- ─────────────────────────────────────────────────────────────────────────────
-- Hyperlinks
-- ─────────────────────────────────────────────────────────────────────────────
config.hyperlink_rules = wezterm.default_hyperlink_rules()

return config
