local wezterm = require("wezterm")
local act     = wezterm.action
local mux     = wezterm.mux

-- Config directory (sibling files live here)
local CFG_DIR     = wezterm.config_dir
local STATE_FILE  = CFG_DIR .. "/session_state.lua"
local PROJECTS    = dofile(CFG_DIR .. "/projects.lua")

local BASH = "C:/Program Files/Git/bin/bash.exe"

-- Default split layout applied when a tab's layout field is nil.
-- Override per-tab in projects.lua with layout = "vsplit"|"hsplit"|"none".
local DEFAULT_LAYOUTS = {
  agent = "vsplit",   -- two side-by-side panes
  dev   = "hsplit",   -- primary top, secondary bottom
  cmd   = "hsplit",
  test  = "hsplit",
  sys   = "hsplit",
}

-- Root folders scanned for immediate subdirectories in the workspace picker.
-- Repos found here that aren't in PROJECTS appear as an "ad-hoc" section.
local REPO_ROOTS = {
  "D:/repo",
  "D:/repo/web",
  "D:/repo/Stock",
}

-- ─────────────────────────────────────────────────────────────────────────────
-- Session state helpers
-- Read: dofile the auto-generated state table (or return nil if missing/invalid)
-- Write: serialize the current workspace+tab layout to a Lua return table
-- ─────────────────────────────────────────────────────────────────────────────

local function read_session_state()
  local ok, result = pcall(dofile, STATE_FILE)
  if ok and type(result) == "table" then return result end
  return nil
end

local function serialize_value(v, indent)
  indent = indent or ""
  local t = type(v)
  if t == "nil"     then return "nil"
  elseif t == "boolean" then return tostring(v)
  elseif t == "number"  then return tostring(v)
  elseif t == "string"  then return string.format("%q", v)
  elseif t == "table"   then
    local inner = indent .. "  "
    local parts = {}
    local is_array = #v > 0
    if is_array then
      for _, item in ipairs(v) do
        table.insert(parts, inner .. serialize_value(item, inner))
      end
      return "{\n" .. table.concat(parts, ",\n") .. "\n" .. indent .. "}"
    else
      for k, val in pairs(v) do
        local key = type(k) == "string"
            and ("[" .. string.format("%q", k) .. "]")
            or  ("[" .. tostring(k) .. "]")
        table.insert(parts, inner .. key .. " = " .. serialize_value(val, inner))
      end
      return "{\n" .. table.concat(parts, ",\n") .. "\n" .. indent .. "}"
    end
  end
  return "nil"
end

local function write_session_state(state)
  local f = io.open(STATE_FILE, "w")
  if not f then return end
  f:write("-- auto-generated by wezterm — do not hand-edit\n")
  f:write("return " .. serialize_value(state) .. "\n")
  f:close()
end

-- Capture current layout across all windows/workspaces
local function capture_state()
  local state = { active_workspace = mux.get_active_workspace(), workspaces = {} }
  for _, win in ipairs(mux.all_windows()) do
    local ws = win:get_workspace()
    if not state.workspaces[ws] then
      local tabs_state   = {}
      local active_tab_id = win:active_tab():tab_id()
      local active_tab_idx = 0
      for tab_idx, tab in ipairs(win:tabs()) do
        local pane    = tab:active_pane()
        local cwd_uri = pane:get_current_working_dir()
        local cwd_str = cwd_uri and cwd_uri.file_path or ""
        local resume_cmd = nil
        for _, proj in ipairs(PROJECTS) do
          if proj.id == ws and proj.tabs[tab_idx] and proj.tabs[tab_idx].resume then
            resume_cmd = proj.tabs[tab_idx].cmd
          end
        end
        if tab:tab_id() == active_tab_id then
          active_tab_idx = tab_idx - 1  -- 0-based, matches ActivateTab(n)
        end
        table.insert(tabs_state, {
          title      = tab:get_title(),
          cwd        = cwd_str,
          resume_cmd = resume_cmd,
        })
      end
      state.workspaces[ws] = {
        active_tab_idx = active_tab_idx,
        tabs           = tabs_state,
      }
    end
  end
  return state
end

-- ─────────────────────────────────────────────────────────────────────────────
-- Startup: open a single plain shell. Workspaces are spawned on-demand.
-- ─────────────────────────────────────────────────────────────────────────────

local HELP_SCRIPT = CFG_DIR:gsub("\\", "/") .. "/help.sh"

wezterm.on("gui-startup", function(_cmd)
  -- Start on the help tab so key bindings are immediately visible.
  -- Press ALT+1-7 to open a workspace; that workspace becomes the active window.
  -- This launcher window stays open as a scratch shell / reference.
  local help_tab, _, window = mux.spawn_window({
    workspace = "launcher",
    args      = { BASH, HELP_SCRIPT },
  })
  help_tab:set_title("help")
  local shell_tab, _ = window:spawn_tab({ args = { BASH, "-l" } })
  shell_tab:set_title("shell")
  help_tab:activate()
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- open_project: switch to a workspace, spawning it with full tab layout if new.
-- ─────────────────────────────────────────────────────────────────────────────

local function workspace_exists(id)
  for _, win in ipairs(mux.all_windows()) do
    if win:get_workspace() == id then return true end
  end
  return false
end

-- Apply pane split to a freshly spawned tab based on layout field.
local function apply_split(tab, layout_override, tab_title, cwd)
  local layout = layout_override
  if layout == nil then
    layout = DEFAULT_LAYOUTS[tab_title]
  end
  if not layout or layout == "none" then return end

  local direction = layout == "vsplit" and "Right" or "Down"
  tab:active_pane():split({ direction = direction, cwd = cwd, args = { BASH, "-l" } })
  -- Return focus to the first (main) pane
  tab:active_pane():activate()
end

local function open_project(proj_id)
  return wezterm.action_callback(function(window, pane)
    if workspace_exists(proj_id) then
      window:perform_action(act.SwitchToWorkspace { name = proj_id }, pane)
      return
    end

    local proj = nil
    for _, p in ipairs(PROJECTS) do
      if p.id == proj_id then proj = p; break end
    end
    if not proj then return end

    local saved   = read_session_state()
    local t1      = proj.tabs[1]
    local t1_args = t1.cmd and { BASH, "-lc", t1.cmd } or { BASH, "-l" }
    if saved and saved.workspaces and saved.workspaces[proj_id] then
      local st = saved.workspaces[proj_id].tabs and saved.workspaces[proj_id].tabs[1]
      if st and st.resume_cmd then t1_args = { BASH, "-lc", st.resume_cmd } end
    end

    -- Switch the CURRENT OS window to the new workspace.
    -- `spawn` seeds the workspace's first tab — no new OS window is created.
    window:perform_action(act.SwitchToWorkspace {
      name  = proj_id,
      spawn = { cwd = proj.cwd, args = t1_args },
    }, pane)

    -- perform_action is asynchronous; wait briefly for the switch to land
    -- before we can manipulate the workspace's tabs via the mux API.
    wezterm.time.call_after(0.15, function()
      local target_win = nil
      for _, win in ipairs(mux.all_windows()) do
        if win:get_workspace() == proj_id then target_win = win; break end
      end
      if not target_win then return end

      local tabs = target_win:tabs()
      if #tabs == 0 then return end

      tabs[1]:set_title(t1.title)
      apply_split(tabs[1], t1.layout, t1.title, proj.cwd)

      for j = 2, #proj.tabs do
        local t    = proj.tabs[j]
        local args = t.cmd and { BASH, "-lc", t.cmd } or { BASH, "-l" }
        if saved and saved.workspaces and saved.workspaces[proj_id] then
          local st = saved.workspaces[proj_id].tabs and saved.workspaces[proj_id].tabs[j]
          if st and st.resume_cmd then args = { BASH, "-lc", st.resume_cmd } end
        end
        local new_tab = target_win:spawn_tab({ cwd = proj.cwd, args = args })
        new_tab:set_title(t.title)
        apply_split(new_tab, t.layout, t.title, proj.cwd)
      end

      -- Restore the tab that was active when this workspace was last closed
      local restore_idx = 0
      if saved and saved.workspaces and saved.workspaces[proj_id] then
        restore_idx = saved.workspaces[proj_id].active_tab_idx or 0
      end
      local all_tabs = target_win:tabs()
      local target_tab = all_tabs[restore_idx + 1] or all_tabs[1]
      if target_tab then target_tab:activate() end
    end)
  end)
end

-- Open any directory path as a workspace (ad-hoc, not in projects.lua).
-- Creates the directory if it doesn't exist, then switches to a new workspace
-- with a single bash shell. The workspace id is derived from the dir basename.
local function open_adhoc(window, pane, dir_path)
  -- normalize slashes, strip trailing separator
  dir_path = dir_path:gsub("\\", "/"):gsub("/+$", "")
  local basename = dir_path:match("([^/]+)$") or dir_path
  local ws_id = basename:lower():gsub("[^%w%-]", "-")

  wezterm.run_child_process({
    "powershell.exe", "-NoProfile", "-Command",
    "New-Item -ItemType Directory -Force -Path '" .. dir_path .. "' | Out-Null",
  })

  if workspace_exists(ws_id) then
    window:perform_action(act.SwitchToWorkspace { name = ws_id }, pane)
    return
  end

  window:perform_action(act.SwitchToWorkspace {
    name  = ws_id,
    spawn = { cwd = dir_path, args = { BASH } },
  }, pane)
end

-- Workspace picker: defined once, shared by both LEGEND and config.keys.
-- Order: [+] new (top) | pinned projects | discovered repos from REPO_ROOTS.
local PICK_WORKSPACE = wezterm.action_callback(function(window, pane)
  -- [+] New workspace always first so it's reachable without scrolling
  local choices = {
    { id = "__new__", label = "[+]  New workspace  (type a path)" },
    { id = "",        label = "─────────────────────────────────────────" },
  }

  -- Pinned projects
  local known_cwds = {}
  for _, p in ipairs(PROJECTS) do
    known_cwds[p.cwd] = true
    local open = workspace_exists(p.id)
    table.insert(choices, {
      id    = p.id,
      label = (open and "● " or "○ ") .. p.label,
    })
  end

  -- Discovered repos: immediate subdirs of REPO_ROOTS not already in PROJECTS.
  -- Glob on Windows doesn't reliably filter dirs-only via trailing slash, so
  -- skip anything with a file extension (repos don't have them; loose files do).
  local discovered = {}
  for _, root in ipairs(REPO_ROOTS) do
    for _, d in ipairs(wezterm.glob(root .. "/*")) do
      local path = d:gsub("[\\/]+$", "")
      local name = path:match("([^/\\]+)$") or ""
      local has_ext = name:match("%.[^./\\]+$")
      if not has_ext and not known_cwds[path] then
        known_cwds[path] = true
        table.insert(discovered, path)
      end
    end
  end

  if #discovered > 0 then
    table.insert(choices, { id = "", label = "── repos ────────────────────────────────" })
    for _, path in ipairs(discovered) do
      local name = path:match("([^/\\]+)$") or path
      table.insert(choices, {
        id    = "__path__:" .. path,
        label = "○ " .. name,
      })
    end
  end

  window:perform_action(act.InputSelector {
    title   = "Workspace  (● open · ○ closed)",
    choices = choices,
    fuzzy   = true,
    action  = wezterm.action_callback(function(w, p2, id, _)
      if not id or id == "" then return end
      if id == "__new__" then
        w:perform_action(act.PromptInputLine {
          description = "Directory path (will be created if missing):",
          action = wezterm.action_callback(function(w2, p3, line)
            if line and line ~= "" then open_adhoc(w2, p3, line) end
          end),
        }, p2)
      else
        local repo_path = id:match("^__path__:(.+)$")
        if repo_path then
          open_adhoc(w, p2, repo_path)
        else
          w:perform_action(open_project(id), p2)
        end
      end
    end),
  }, pane)
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- Periodic state flush (every 30s) so abrupt kills don't lose context
-- ─────────────────────────────────────────────────────────────────────────────

local function schedule_state_flush()
  wezterm.time.call_after(30, function()
    write_session_state(capture_state())
    schedule_state_flush() -- reschedule indefinitely
  end)
end

wezterm.on("gui-attached", function(_domain)
  schedule_state_flush()
end)

-- Also flush on graceful close
wezterm.on("window-close-requested", function(window, _pane)
  write_session_state(capture_state())
  window:perform_action(act.CloseCurrentWindow, window:active_pane())
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- Appearance
-- ─────────────────────────────────────────────────────────────────────────────

local config = wezterm.config_builder()

-- ── Crimson Noir — custom palette ────────────────────────────────────────────
-- To swap back to a built-in: comment out config.colors and set config.color_scheme instead.
config.colors = {
  -- Base layer
  background    = "#0e0014",  -- purple-black void
  foreground    = "#edd9f5",  -- warm purple-tinted white

  cursor_bg     = "#c4185c",  -- saturated crimson-magenta
  cursor_fg     = "#0e0014",
  cursor_border = "#c4185c",

  selection_bg  = "#8b1aaa",  -- regal purple selection
  selection_fg  = "#edd9f5",

  split         = "#6b3080",  -- pane divider

  -- 16 ANSI slots — programs write to these for syntax / git / ls colors
  --   slot 0  black      slot 1  red        slot 2  green      slot 3  yellow
  --   slot 4  blue       slot 5  magenta    slot 6  cyan       slot 7  white
  ansi = {
    "#200030",  -- 0  black  (used as bg variant in some apps)
    "#c4185c",  -- 1  red    → our crimson-magenta (errors, deletions)
    "#1f8c5a",  -- 2  green  → muted forest green  (additions, success)
    "#b87333",  -- 3  yellow → copper-gold          (warnings, modified)
    "#2a6fa8",  -- 4  blue   → steel blue           (info, types)
    "#8b1aaa",  -- 5  magenta→ deep regal purple    (keywords, specials)
    "#2a7a8c",  -- 6  cyan   → dark teal            (strings, paths)
    "#c8b8d8",  -- 7  white  → purple-tinted grey   (normal text)
  },
  brights = {
    "#6b3080",  -- 8  bright black  (comments, borders)
    "#e8378e",  -- 9  bright red    → hot rose-red   (bold errors)
    "#27b870",  -- 10 bright green  → vivid green    (bold success)
    "#d4943a",  -- 11 bright yellow → warm amber     (bold warnings)
    "#4a9fd4",  -- 12 bright blue   → sky blue       (bold info)
    "#b040d0",  -- 13 bright magenta→ vivid purple   (bold specials)
    "#3aadcc",  -- 14 bright cyan   → vivid teal     (bold strings)
    "#edd9f5",  -- 15 bright white  → primary text   (bold normal)
  },

  -- Tab bar
  tab_bar = {
    background = "#160022",
    active_tab = {
      bg_color  = "#0e0014",
      fg_color  = "#e8378e",
      intensity = "Bold",
    },
    inactive_tab = {
      bg_color = "#160022",
      fg_color = "#6b3080",
    },
    inactive_tab_hover = {
      bg_color = "#200030",
      fg_color = "#c8b8d8",
    },
  },
}
config.font             = wezterm.font("JetBrains Mono", { weight = "Regular" })
config.harfbuzz_features = { "calt=1", "clig=1", "liga=1" }
config.font_size         = 13.0
config.line_height       = 1.1
config.use_fancy_tab_bar = false
config.tab_bar_at_bottom = false
config.tab_max_width     = 22
config.show_new_tab_button_in_tab_bar = false
config.window_padding    = { left = 6, right = 6, top = 4, bottom = 4 }
config.window_decorations = "TITLE | RESIZE"
config.initial_cols      = 120
config.initial_rows      = 34
config.default_cursor_style = "BlinkingBar"
config.cursor_blink_rate = 500
config.scrollback_lines  = 20000
config.audible_bell      = "Disabled"
config.default_prog      = { BASH, "-l" }

-- ─────────────────────────────────────────────────────────────────────────────
-- Status bar
-- Left : currently OPEN workspaces only — active=crimson, other=muted, ●=attention
-- Right: persistent legend hint + clock
-- ─────────────────────────────────────────────────────────────────────────────

wezterm.on("update-right-status", function(window, _pane)
  local current_ws = window:active_workspace()

  -- Collect open workspaces, preserving projects.lua order
  local open_wins = {}
  for _, win in ipairs(mux.all_windows()) do
    open_wins[win:get_workspace()] = win
  end

  local left_parts = { { Text = " " } }
  local any_open   = false

  for _, proj in ipairs(PROJECTS) do
    local win = open_wins[proj.id]
    if not win then goto continue end   -- skip closed workspaces

    any_open = true
    local is_active = proj.id == current_ws
    local attention = false
    for _, tab in ipairs(win:tabs()) do
      for _, p in ipairs(tab:panes()) do
        if p:has_unseen_output() then attention = true; break end
      end
      if attention then break end
    end

    local label = string.format(" %s%s ", attention and "● " or "", proj.label)

    if is_active then
      table.insert(left_parts, { Attribute = { Intensity = "Bold" } })
      table.insert(left_parts, { Foreground = { Color = "#e8378e" } })   -- crimson: focused
    elseif attention then
      table.insert(left_parts, { Attribute = { Intensity = "Normal" } })
      table.insert(left_parts, { Foreground = { Color = "#d4943a" } })   -- amber: needs attention
    else
      table.insert(left_parts, { Attribute = { Intensity = "Normal" } })
      table.insert(left_parts, { Foreground = { Color = "#9b6aaa" } })   -- muted rose: open
    end
    table.insert(left_parts, { Text = label })

    ::continue::
  end

  -- Nothing open yet: nudge user toward the picker
  if not any_open then
    table.insert(left_parts, { Attribute = { Intensity = "Bold" } })
    table.insert(left_parts, { Foreground = { Color = "#c4185c" } })
    table.insert(left_parts, { Text = " ALT+P" })
    table.insert(left_parts, { Foreground = { Color = "#6b3080" } })
    table.insert(left_parts, { Text = " open a workspace " })
  end

  window:set_left_status(wezterm.format(left_parts))

  -- Right: persistent legend reminder + clock
  local time = wezterm.strftime "%H:%M"
  window:set_right_status(wezterm.format({
    { Attribute = { Intensity = "Normal" } },
    { Foreground = { Color = "#6b3080" } },
    { Text = "ALT+/  legend" },
    { Foreground = { Color = "#3a1a4a" } },
    { Text = "  │  " },
    { Foreground = { Color = "#6b3080" } },
    { Text = time .. "  " },
  }))
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- Tab title renderer
-- ─────────────────────────────────────────────────────────────────────────────

wezterm.on("format-tab-title", function(tab, _tabs, _panes, _cfg, _hover, max_width)
  local title = tab.tab_title
  if not title or #title == 0 then title = tab.active_pane.title end
  if #title > max_width - 4 then
    title = wezterm.truncate_right(title, max_width - 4)
  end
  local idx = tab.tab_index + 1

  -- Active tab: bright. Inactive with unseen output: amber (matches status bar). Idle: muted.
  local fg
  if tab.is_active then
    fg = "#c0caf5"
  elseif tab.active_pane.has_unseen_output then
    fg = "#d4943a"
  else
    fg = "#565f89"
  end

  return {
    { Background = { Color = tab.is_active and "#1a1b26" or "#16161e" } },
    { Foreground = { Color = fg } },
    { Text = " " .. idx .. ":" .. title .. " " },
  }
end)

-- Toast notification on terminal bell.
-- Any program can trigger this with: printf '\a'
-- Shell prompt hooks, Claude Code stop hooks, and long-running scripts use this.
wezterm.on("bell", function(window, pane)
  local tab   = pane:tab()
  local label = tab and tab:get_title() or "terminal"
  local ws    = window:active_workspace()
  window:toast_notification(
    "WezTerm  ·  " .. ws,
    label .. " — needs attention",
    nil,
    4000
  )
end)

-- ─────────────────────────────────────────────────────────────────────────────
-- Key bindings
-- LEADER = ALT+Z  (1.5 s window — left-hand only, no OS conflicts)
-- ─────────────────────────────────────────────────────────────────────────────

config.leader = { key = "z", mods = "ALT", timeout_milliseconds = 1500 }

-- Workspace picker choices built dynamically inside ALT+P callback (live open/closed status).

-- ─────────────────────────────────────────────────────────────────────────────
-- Macro legend (shown by LEADER ?)
-- Add any new binding here alongside its keys entry below so the legend stays in sync.
-- ─────────────────────────────────────────────────────────────────────────────

-- LEGEND: single source of truth — each entry carries its WezTermAction.
-- Selecting an entry in the ALT+/ overlay executes it; separators (action=nil) are no-ops.
local LEGEND = {
  { keys = "ALT  P",          desc = "Open workspace  (● open · ○ closed)",  action = PICK_WORKSPACE },
  { keys = "ALT  ↑",          desc = "Previous workspace",                    action = act.SwitchWorkspaceRelative(-1) },
  { keys = "ALT  ↓",          desc = "Next workspace",                        action = act.SwitchWorkspaceRelative(1)  },
  { keys = "ALT  0",          desc = "Launcher / help",                       action = act.SwitchToWorkspace { name = "launcher" } },
  { keys = "─────────────────────", desc = "─── Tabs ────────────────────────",  action = nil },
  { keys = "ALT  ←",          desc = "Previous tab",                          action = act.ActivateTabRelative(-1) },
  { keys = "ALT  →",          desc = "Next tab",                              action = act.ActivateTabRelative(1)  },
  { keys = "CTRL+SHIFT  T",   desc = "New tab",                               action = act.SpawnTab "CurrentPaneDomain" },
  { keys = "CTRL+SHIFT  W",   desc = "Close tab",                             action = act.CloseCurrentTab { confirm = true } },
  { keys = "─────────────────────", desc = "─── Panes ───────────────────────",  action = nil },
  { keys = "LEADER  |",       desc = "Split pane right",                      action = act.SplitHorizontal { domain = "CurrentPaneDomain" } },
  { keys = "LEADER  -",       desc = "Split pane down",                       action = act.SplitVertical   { domain = "CurrentPaneDomain" } },
  { keys = "LEADER  h",       desc = "Focus pane left",                       action = act.ActivatePaneDirection "Left"  },
  { keys = "LEADER  j",       desc = "Focus pane down",                       action = act.ActivatePaneDirection "Down"  },
  { keys = "LEADER  k",       desc = "Focus pane up",                         action = act.ActivatePaneDirection "Up"    },
  { keys = "LEADER  l",       desc = "Focus pane right",                      action = act.ActivatePaneDirection "Right" },
  { keys = "LEADER  z",       desc = "Zoom / unzoom pane",                    action = act.TogglePaneZoomState },
  { keys = "─────────────────────", desc = "─── Utility ─────────────────────",  action = nil },
  { keys = "ALT  /",          desc = "Show this legend",                      action = nil },
  { keys = "LEADER  c",       desc = "Copy mode (vi scroll + select)",        action = act.ActivateCopyMode },
  { keys = "CTRL+SHIFT  C",   desc = "Copy to clipboard",                     action = act.CopyTo "Clipboard" },
  { keys = "CTRL+SHIFT  V",   desc = "Paste from clipboard",                  action = act.PasteFrom "Clipboard" },
  { keys = "CTRL+SHIFT  F",   desc = "Fullscreen",                            action = act.ToggleFullScreen },
  { keys = "CTRL  +",         desc = "Font size increase",                    action = act.IncreaseFontSize },
  { keys = "CTRL  -",         desc = "Font size decrease",                    action = act.DecreaseFontSize },
  { keys = "CTRL  0",         desc = "Font size reset",                       action = act.ResetFontSize },
}

-- ─────────────────────────────────────────────────────────────────────────────
-- Key table — actions reference LEGEND entries or PICK_WORKSPACE directly.
-- ─────────────────────────────────────────────────────────────────────────────

config.keys = {

  -- ── Legend overlay: ALT+/ opens picker; Enter on any entry executes it ────
  {
    key = "/", mods = "ALT",
    action = wezterm.action_callback(function(window, pane)
      local choices = {}
      for i, entry in ipairs(LEGEND) do
        table.insert(choices, {
          id    = tostring(i),
          label = string.format("%-24s  %s", entry.keys, entry.desc),
        })
      end
      window:perform_action(act.InputSelector {
        title   = "Key Bindings — Enter to run · Esc to dismiss",
        choices = choices,
        fuzzy   = true,
        action  = wezterm.action_callback(function(w, p2, id, _)
          local idx   = tonumber(id)
          local entry = idx and LEGEND[idx]
          if entry and entry.action then
            w:perform_action(entry.action, p2)
          end
        end),
      }, pane)
    end),
  },

  -- ── Workspaces ────────────────────────────────────────────────────────────
  { key = "0",         mods = "ALT", action = LEGEND[4].action  },  -- launcher
  { key = "UpArrow",   mods = "ALT", action = LEGEND[2].action  },  -- prev workspace
  { key = "DownArrow", mods = "ALT", action = LEGEND[3].action  },  -- next workspace
  { key = "p",         mods = "ALT", action = LEGEND[1].action  },  -- picker

  -- ── Tabs ──────────────────────────────────────────────────────────────────
  { key = "LeftArrow",  mods = "ALT",       action = LEGEND[6].action  },  -- prev tab
  { key = "RightArrow", mods = "ALT",       action = LEGEND[7].action  },  -- next tab
  { key = "t",          mods = "CTRL|SHIFT", action = LEGEND[8].action  },  -- new tab
  { key = "w",          mods = "CTRL|SHIFT", action = LEGEND[9].action  },  -- close tab

  -- ── Panes ─────────────────────────────────────────────────────────────────
  { key = "|", mods = "LEADER", action = LEGEND[11].action },  -- split right
  { key = "-", mods = "LEADER", action = LEGEND[12].action },  -- split down
  { key = "h", mods = "LEADER", action = LEGEND[13].action },  -- focus left
  { key = "j", mods = "LEADER", action = LEGEND[14].action },  -- focus down
  { key = "k", mods = "LEADER", action = LEGEND[15].action },  -- focus up
  { key = "l", mods = "LEADER", action = LEGEND[16].action },  -- focus right
  { key = "z", mods = "LEADER", action = LEGEND[17].action },  -- zoom

  -- ── Utility ───────────────────────────────────────────────────────────────
  { key = "c", mods = "LEADER",     action = LEGEND[20].action },  -- copy mode
  { key = "c", mods = "CTRL|SHIFT", action = LEGEND[21].action },  -- copy
  { key = "v", mods = "CTRL|SHIFT", action = LEGEND[22].action },  -- paste
  { key = "f", mods = "CTRL|SHIFT", action = LEGEND[23].action },  -- fullscreen
  { key = "=", mods = "CTRL",       action = LEGEND[24].action },  -- font +
  { key = "-", mods = "CTRL",       action = LEGEND[25].action },  -- font -
  { key = "0", mods = "CTRL",       action = LEGEND[26].action },  -- font reset
}

-- ─────────────────────────────────────────────────────────────────────────────
-- Hyperlinks
-- ─────────────────────────────────────────────────────────────────────────────
config.hyperlink_rules = wezterm.default_hyperlink_rules()

-- ─────────────────────────────────────────────────────────────────────────────
-- Duplicate binding validator
-- Scans config.keys for (key, mods) collisions at load time.
-- Warnings appear in WezTerm's log viewer: Help > Show Debug Log Overlay
-- ─────────────────────────────────────────────────────────────────────────────
do
  local seen = {}
  for i, b in ipairs(config.keys) do
    local id = string.format("[%s] %s", b.mods or "NONE", b.key)
    if seen[id] then
      wezterm.log_warn(string.format(
        "DUPLICATE BINDING at entry %d — %s (first seen at entry %d). Last definition wins.",
        i, id, seen[id]
      ))
    else
      seen[id] = i
    end
  end
end

return config
